---
dockerConfig:
  host: tcp://172.20.51.24:2375
#  host: tcp://172.30.126.201:2375

harborConfig:
  endpoint: harbor.mdt.etri.re.kr
  userId: admin
  password: Mdt2024^^
  email: admin@192.168.0.70
   
jdbcConfig:
  system: postgresql
  host: 192.168.0.7
  port: 5432
  user: mdt
  password: Mdt2024^^
  database: mdt
   
kubernetesConfig:
  host: 192.168.0.60
  port: 6443
  
instanceProject: mdt-instance
